{{- if .Values.ExternalSecrets.enabled }}
  {{- range .Values.ExternalSecrets.secrets }}
apiVersion: external-secrets.io/v1alpha1 
kind: ExternalSecret
metadata:
  name: {{ .name}}
spec:
  {{- if .refreshInterval }}
  refreshInterval: {{ .refreshInterval}}
  {{- end}}
  secretStoreRef:
    name: {{ .secretStoreName}}
    kind: SecretStore
  target:
    name: {{ .name}}
    creationPolicy: Owner
  data:
  {{- range .secretData }}
  - secretKey: {{ .secretKey }}
    remoteRef:
        key: {{.awssmsecretname}}
        property: {{.property}} 
{{- end}}
{{- end}}
{{- end}}